//! CLI subcommands implementation for Plexis.
//!
//! Subcommands:
//! - `init [path]`: Initializes a workspace in the target directory, detecting project characteristics.
//! - `serve`: Launches the operational HTTP server control plane.
//! - `status`: Inspects authoritative storage and prints system and workspace operational status.

use clap::{Parser, Subcommand};
use std::net::SocketAddr;
use std::path::{Path, PathBuf};
use std::sync::Arc;
use tracing::info;
use tracing_subscriber::{layer::SubscriberExt, util::SubscriberInitExt};

use plexis_core::ids::MissionId;
use plexis_core::Workspace;
use plexis_storage::traits::{AgentStore, MissionStore, TaskStore, WorkflowStore, WorkspaceStore};
use plexis_storage::SqliteStore;

use crate::routes::create_router;
use crate::state::AppState;

#[derive(Parser, Debug)]
#[command(name = "sentinel")]
#[command(version)]
#[command(about = "Sentinel — Autonomous Software Engineering Execution Engine & Control Plane", long_about = None)]
pub struct Cli {
    #[command(subcommand)]
    pub command: Option<Commands>,
}

#[derive(Subcommand, Debug)]
pub enum Commands {
    /// Initialize a project workspace for Sentinel
    Init {
        /// Target directory to initialize as workspace (defaults to current working directory)
        path: Option<PathBuf>,
        /// Friendly workspace name
        #[arg(short, long)]
        name: Option<String>,
        /// Path to the authoritative database
        #[arg(long, default_value = "plexis.db")]
        db: String,
    },
    /// Start the Sentinel operational control plane server
    Serve {
        /// Bind host address
        #[arg(long, default_value = "127.0.0.1")]
        host: String,
        /// Listen port
        #[arg(short, long, default_value_t = 3000)]
        port: u16,
        /// Path to SQLite database file or :memory:
        #[arg(long, default_value = "plexis.db")]
        db: String,
        /// Optional authentication bearer token
        #[arg(long)]
        auth_token: Option<String>,
    },
    /// Inspect system and workspace operational status
    Status {
        /// Path to SQLite database file
        #[arg(long, default_value = "plexis.db")]
        db: String,
    },
    /// Manage autonomous engineering missions
    Mission {
        #[command(subcommand)]
        subcommand: MissionCommands,
        /// Path to SQLite database file
        #[arg(long, default_value = "plexis.db")]
        db: String,
    },
    /// Run deep startup and recovery reconciliation
    Reconcile {
        /// Path to SQLite database file
        #[arg(long, default_value = "plexis.db")]
        db: String,
    },
}

#[derive(Subcommand, Debug)]
pub enum MissionCommands {
    /// Create and dispatch a new autonomous mission
    Create {
        /// Target workspace path or repository directory
        path: PathBuf,
        /// Mission objective prompt
        #[arg(short, long)]
        objective: String,
        /// Mission title
        #[arg(short, long)]
        title: Option<String>,
        /// Automatically start the mission
        #[arg(long, default_value_t = true)]
        auto_start: bool,
    },
    /// Inspect mission status, cycle progress, and checkpoints
    Status {
        /// Mission ID
        id: String,
    },
    /// Show the Git diff generated by the mission
    Diff {
        /// Mission ID
        id: String,
    },
    /// Inspect the comprehensive review package before acceptance
    Review {
        /// Mission ID
        id: String,
    },
    /// Explicitly accept a verified mission result
    Accept {
        /// Mission ID
        id: String,
        /// Immediately integrate into target branch after acceptance
        #[arg(long)]
        integrate: bool,
        /// Target git branch (defaults to main)
        #[arg(long)]
        branch: Option<String>,
        /// Optional commit message
        #[arg(long)]
        message: Option<String>,
    },
    /// Non-destructively reject a mission result with audit reason
    Reject {
        /// Mission ID
        id: String,
        /// Reason for rejection
        #[arg(short, long)]
        reason: String,
        /// Request another autonomous attempt / replan
        #[arg(long)]
        replan: bool,
    },
    /// Safely integrate an accepted mission into target branch
    Integrate {
        /// Mission ID
        id: String,
        /// Target git branch to merge into (defaults to main)
        #[arg(long)]
        branch: Option<String>,
        /// Optional custom commit message
        #[arg(long)]
        message: Option<String>,
    },
}

pub async fn run_cli() -> Result<(), Box<dyn std::error::Error>> {
    let cli = Cli::parse();

    match cli.command {
        Some(Commands::Mission { subcommand, db }) => {
            handle_mission_command(subcommand, &db).await?;
        }
        Some(Commands::Init { path, name, db }) => {
            init_workspace(path, name, &db).await?;
        }
        Some(Commands::Serve {
            host,
            port,
            db,
            auth_token,
        }) => {
            run_server(&host, port, &db, auth_token).await?;
        }
        Some(Commands::Status { db }) => {
            show_status(&db).await?;
        }
        Some(Commands::Reconcile { db }) => {
            let store = SqliteStore::open(&db)?;
            let state = AppState::new(store);
            let report = state.reconcile_startup().await?;
            println!("Reconciliation Report:");
            println!(
                "  Expired leases reclaimed: {}",
                report.expired_leases_reclaimed.len()
            );
            println!(
                "  Tasks unassigned:         {}",
                report.tasks_unassigned.len()
            );
            println!(
                "  Resumable workflows:      {}",
                report.resumable_workflows.len()
            );
            println!(
                "  Resumable missions:       {}",
                report.resumable_missions.len()
            );
            println!(
                "  Missions reconciled:      {}",
                report.missions_reconciled.len()
            );
            println!(
                "  Commands reconciled:      {}",
                report.commands_reconciled.len()
            );
            println!(
                "  Executions reconciled:    {}",
                report.executions_reconciled.len()
            );
            if !report.anomalies.is_empty() {
                println!("  Anomalies: {:?}", report.anomalies);
            }
        }
        None => {
            // Default behavior: run server with environment/default settings
            let db_path =
                std::env::var("PLEXIS_DB_PATH").unwrap_or_else(|_| "plexis.db".to_string());
            let port = std::env::var("PORT")
                .ok()
                .and_then(|p| p.parse::<u16>().ok())
                .unwrap_or(3000);
            let auth_token = std::env::var("SENTINEL_AUTH_TOKEN")
                .or_else(|_| std::env::var("PLEXIS_AUTH_TOKEN"))
                .ok();
            run_server("127.0.0.1", port, &db_path, auth_token).await?;
        }
    }

    Ok(())
}

async fn init_workspace(
    target_path: Option<PathBuf>,
    custom_name: Option<String>,
    db_path: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    let target = target_path
        .unwrap_or_else(|| std::env::current_dir().unwrap_or_else(|_| PathBuf::from(".")));
    let canonical = std::fs::canonicalize(&target).unwrap_or(target);
    let ws_name = custom_name.unwrap_or_else(|| {
        canonical
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or("workspace")
            .to_string()
    });

    println!(
        "Initializing Sentinel workspace in: {}",
        canonical.display()
    );

    // Create .plexis directory and config
    let plexis_dir = canonical.join(".plexis");
    std::fs::create_dir_all(&plexis_dir)?;

    let config_file = plexis_dir.join("config.json");
    if !config_file.exists() {
        let default_config = serde_json::json!({
            "name": ws_name,
            "version": "1.0",
            "security": {
                "max_execution_time_secs": 1800,
                "allow_network": false,
                "require_approval_for_destructive": true
            }
        });
        std::fs::write(&config_file, serde_json::to_string_pretty(&default_config)?)?;
        println!("Created {}", config_file.display());
    }

    // Register workspace in store
    let store = if db_path == ":memory:" {
        SqliteStore::open_in_memory()?
    } else {
        SqliteStore::open(db_path)?
    };

    let mut ws = Workspace::new(&ws_name, canonical.clone());
    if let Ok(meta) = crate::git::discover_git_metadata(&canonical) {
        ws.vcs = meta;
    }
    ws.metadata = serde_json::json!({ "is_default": true });

    store.create_workspace(&ws).await?;
    println!(
        "Registered workspace '{}' [{}] in {}",
        ws.name, ws.id, db_path
    );
    println!("Workspace initialized successfully.");

    Ok(())
}

async fn show_status(db_path: &str) -> Result<(), Box<dyn std::error::Error>> {
    if !Path::new(db_path).exists() && db_path != ":memory:" {
        println!("Database not found at: {}", db_path);
        println!("Run 'sentinel init' or start 'sentinel serve' to create one.");
        return Ok(());
    }

    let store = SqliteStore::open(db_path)?;
    let workspaces = store.list_workspaces().await?;
    let workflows = store.list_workflows().await?;
    let mut total_tasks = 0;
    for wf in &workflows {
        if let Ok(tasks) = store.list_tasks_by_workflow(&wf.id).await {
            total_tasks += tasks.len();
        }
    }
    let agents = store.list_agents().await?;

    println!("============================================================");
    println!("                 SENTINEL SYSTEM STATUS                       ");
    println!("============================================================");
    println!("Authoritative Database : {}", db_path);
    println!("Total Workspaces       : {}", workspaces.len());
    println!("Total Workflows        : {}", workflows.len());
    println!("Total Tasks            : {}", total_tasks);
    println!("Active Agents          : {}", agents.len());
    println!("------------------------------------------------------------");
    if workspaces.is_empty() {
        println!("No workspaces registered. Use 'sentinel init' to register one.");
    } else {
        println!("Workspaces:");
        for ws in &workspaces {
            let default_flag = if ws
                .metadata
                .get("is_default")
                .and_then(|v| v.as_bool())
                .unwrap_or(false)
            {
                " (default)"
            } else {
                ""
            };
            let vcs = if let Some(ref b) = ws.vcs.branch {
                let head = ws.vcs.head_sha.as_deref().unwrap_or("unknown");
                format!(" [git: {}@{}]", b, &head[..7.min(head.len())])
            } else {
                String::new()
            };
            println!(
                "  • {} [{}]{} -> {}{}",
                ws.name,
                ws.id,
                default_flag,
                ws.canonical_path.display(),
                vcs
            );
        }
    }
    println!("============================================================");

    Ok(())
}

async fn run_server(
    host: &str,
    port: u16,
    db_path: &str,
    auth_token: Option<String>,
) -> Result<(), Box<dyn std::error::Error>> {
    tracing_subscriber::registry()
        .with(
            tracing_subscriber::EnvFilter::try_from_default_env().unwrap_or_else(|_| "info".into()),
        )
        .with(tracing_subscriber::fmt::layer())
        .init();

    let ip: std::net::IpAddr = host
        .parse()
        .map_err(|e| format!("Invalid bind host address '{}': {}", host, e))?;

    let effective_auth_token = auth_token.filter(|t| !t.trim().is_empty()).or_else(|| {
        std::env::var("SENTINEL_AUTH_TOKEN")
            .or_else(|_| std::env::var("PLEXIS_AUTH_TOKEN"))
            .ok()
            .filter(|t| !t.trim().is_empty())
    });

    if !ip.is_loopback() && effective_auth_token.is_none() {
        eprintln!(
            "================================================================================"
        );
        eprintln!("FATAL SECURITY ERROR: NON-LOOPBACK BIND REQUIRES AUTHENTICATION");
        eprintln!(
            "================================================================================"
        );
        eprintln!(
            "Sentinel attempted to bind to external address '{}' without authentication.",
            host
        );
        eprintln!(
            "Binding to an external network interface without an authentication token exposes"
        );
        eprintln!(
            "local file modification, shell execution, and the control plane to remote attack."
        );
        eprintln!();
        eprintln!(
            "To start Sentinel on a non-loopback interface, provide an authentication token via:"
        );
        eprintln!("  1. CLI flag:            --auth-token <SECRET_TOKEN>");
        eprintln!("  2. Environment variable: SENTINEL_AUTH_TOKEN=<SECRET_TOKEN>");
        eprintln!(
            "================================================================================"
        );
        return Err(format!(
            "FATAL SECURITY ERROR: Server configured to bind to non-loopback address '{}' without authentication. Provide --auth-token or set SENTINEL_AUTH_TOKEN.",
            host
        ).into());
    }

    info!("Opening authoritative storage at: {}", db_path);
    let store = if db_path == ":memory:" {
        SqliteStore::open_in_memory()?
    } else {
        SqliteStore::open(db_path)?
    };

    let mut state = AppState::new(store).with_bind_host(host.to_string(), ip.is_loopback());

    if let Some(ref tok) = effective_auth_token {
        info!("Hardened token authentication enabled");
        state = state.with_auth_token(Some(tok.clone()));
    }

    info!("Running startup and recovery reconciliation...");
    match state.reconcile_startup().await {
        Ok(report) => {
            info!(
                "Startup reconciliation complete: reclaimed {} leases, unassigned {} tasks, reconciled {} missions",
                report.expired_leases_reclaimed.len(),
                report.tasks_unassigned.len(),
                report.missions_reconciled.len()
            );
        }
        Err(e) => {
            tracing::warn!("Startup reconciliation warning: {}", e);
        }
    }

    let app = create_router(state);

    let addr = SocketAddr::from((ip, port));
    info!("Sentinel API server listening on http://{}", addr);

    let listener = tokio::net::TcpListener::bind(addr).await?;
    axum::serve(listener, app).await?;

    Ok(())
}

async fn handle_mission_command(
    subcommand: MissionCommands,
    db_path: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    let store = Arc::new(SqliteStore::open(db_path)?);
    let state = AppState::with_store(store.clone());

    match subcommand {
        MissionCommands::Create {
            path,
            objective,
            title,
            auto_start,
        } => {
            let canonical = path.canonicalize()?;
            let ws_name = canonical
                .file_name()
                .map(|n| n.to_string_lossy().to_string())
                .unwrap_or_else(|| "default_workspace".to_string());

            let workspaces = store.list_workspaces().await?;
            let ws_id =
                if let Some(existing) = workspaces.iter().find(|w| w.canonical_path == canonical) {
                    existing.id
                } else {
                    let ws = Workspace::new(ws_name, canonical.clone());
                    store.create_workspace(&ws).await?;
                    println!("Created workspace: {} ({})", ws.name, ws.id);
                    ws.id
                };

            let title_str = title.unwrap_or_else(|| {
                format!(
                    "Mission: {}",
                    objective.chars().take(40).collect::<String>()
                )
            });
            let mut mission = state
                .mission_engine
                .create_mission(title_str, objective, Some(ws_id), None, None)
                .await?;

            if let Ok(status) = crate::git::get_git_status(&canonical) {
                if let Some(sha) = status.head_commit {
                    mission.metadata["initial_commit"] = serde_json::json!(sha);
                    store.update_mission(&mission).await?;
                }
            }

            if auto_start {
                mission = state.mission_engine.start_mission(mission.id).await?;
                println!(
                    "Mission {} created and started in state '{}'",
                    mission.id, mission.state
                );
            } else {
                println!(
                    "Mission {} created in state '{}'",
                    mission.id, mission.state
                );
            }
        }
        MissionCommands::Status { id } => {
            let mission_id: MissionId = id.parse()?;
            let mission = store
                .get_mission(&mission_id)
                .await?
                .ok_or_else(|| format!("Mission '{}' not found", id))?;

            let latest_ckpt = state
                .mission_engine
                .checkpoint_manager()
                .get_latest_checkpoint(&mission_id)
                .await?;

            let cycles = store.list_cycles(&mission_id).await?;

            println!("==================================================");
            println!("Mission ID:        {}", mission.id);
            println!("Title:             {}", mission.title);
            println!("State:             {}", mission.state);
            println!("Cycle Index:       {}", mission.cycle_index);
            println!("Cycles Total:      {}", cycles.len());
            println!("Health:            {:?}", mission.health_status);
            println!(
                "Verified Commit:   {}",
                mission.latest_verified_commit.as_deref().unwrap_or("none")
            );
            if let Some(ref outcome) = mission.final_outcome {
                println!("Outcome Success:   {}", outcome.success);
                println!("Outcome Summary:   {}", outcome.summary);
            }
            if let Some(ckpt) = latest_ckpt {
                println!("Latest Checkpoint: Cycle {}", ckpt.cycle_index);
            }
            println!("==================================================");
        }
        MissionCommands::Diff { id } => {
            let mission_id: MissionId = id.parse()?;
            let mission = store
                .get_mission(&mission_id)
                .await?
                .ok_or_else(|| format!("Mission '{}' not found", id))?;

            let ws_id = mission
                .workspace_id
                .ok_or("Mission is not bound to a workspace")?;
            let ws = store
                .get_workspace(&ws_id)
                .await?
                .ok_or("Workspace not found")?;

            let base_commit = mission
                .metadata
                .get("initial_commit")
                .and_then(|v| v.as_str());

            let diff_res = if let Some(base) = base_commit {
                crate::git::get_git_diff_against(&ws.canonical_path, base)?
            } else {
                crate::git::get_git_diff(&ws.canonical_path, false)?
            };

            println!("--- Git Diff for Mission {} ---", mission_id);
            println!("Files Changed: {:?}", diff_res.files_changed);
            println!(
                "Insertions: {}, Deletions: {}",
                diff_res.insertions, diff_res.deletions
            );
            println!("\n{}", diff_res.diff);
        }
        MissionCommands::Review { id } => {
            let mission_id: MissionId = id.parse()?;
            let mission = store
                .get_mission(&mission_id)
                .await?
                .ok_or_else(|| format!("Mission '{}' not found", id))?;

            println!("================================================================");
            println!("               SENTINEL MISSION REVIEW PACKAGE                   ");
            println!("================================================================");
            println!("Mission ID:   {}", mission.id);
            println!("Title:        {}", mission.title);
            println!("Objective:    {}", mission.objective);
            println!("State:        {}", mission.state);
            println!("Health:       {:?}", mission.health_status);
            println!("Duration:     {}s", mission.budget_consumed.duration_secs);
            println!("Cycles:       {}", mission.cycle_index + 1);
            println!("Executions:   {}", mission.budget_consumed.total_executions);
            println!(
                "Recoveries:   {}",
                mission.budget_consumed.recovery_attempts
            );

            if let Some(ref sha) = mission.latest_verified_commit {
                println!("Final Commit: {}", sha);
            } else {
                println!("Final Commit: None");
            }

            if let Some(ref outcome) = mission.final_outcome {
                println!("\nVerification Outcome:");
                println!("  Success:    {}", outcome.success);
                println!("  Reason:     {}", outcome.completion_reason);
                println!("  Summary:    {}", outcome.summary);
            }

            if let Some(ws_id) = mission.workspace_id {
                if let Ok(Some(ws)) = store.get_workspace(&ws_id).await {
                    println!("\nRepository:   {}", ws.canonical_path.display());
                    let base_commit = mission
                        .metadata
                        .get("initial_commit")
                        .and_then(|v| v.as_str());
                    if let Ok(diff_res) = if let Some(base) = base_commit {
                        crate::git::get_git_diff_against(&ws.canonical_path, base)
                    } else {
                        crate::git::get_git_diff(&ws.canonical_path, false)
                    } {
                        println!("Files Changed: {:?}", diff_res.files_changed);
                        println!(
                            "Insertions:   {}, Deletions: {}",
                            diff_res.insertions, diff_res.deletions
                        );
                    }
                }
            }

            println!("================================================================");
            match mission.state {
                plexis_core::state::MissionState::AwaitingAcceptance => {
                    println!("\nACTION REQUIRED: Mission is verified and awaiting explicit human acceptance.");
                    println!(
                        "  Accept & Integrate: sentinel mission accept {} --integrate",
                        mission_id
                    );
                    println!(
                        "  Accept Only:        sentinel mission accept {}",
                        mission_id
                    );
                    println!(
                        "  Reject:             sentinel mission reject {} -r \"reason\"",
                        mission_id
                    );
                }
                plexis_core::state::MissionState::Accepted => {
                    println!(
                        "\nACTION REQUIRED: Mission has been accepted. Ready for integration."
                    );
                    println!(
                        "  Integrate:          sentinel mission integrate {}",
                        mission_id
                    );
                }
                plexis_core::state::MissionState::Integrating => {
                    println!("\nSTATUS: Mission is currently being integrated into the target repository.");
                }
                plexis_core::state::MissionState::Integrated => {
                    println!("\nSTATUS: Mission deliverable is already integrated into the target repository.");
                }
                other => {
                    println!("\nSTATUS: Mission is in state '{}'.", other);
                }
            }
        }
        MissionCommands::Accept {
            id,
            integrate,
            branch,
            message,
        } => {
            let mission_id: MissionId = id.parse()?;
            let mut mission = store
                .get_mission(&mission_id)
                .await?
                .ok_or_else(|| format!("Mission '{}' not found", id))?;

            if mission.state == plexis_core::state::MissionState::Integrated {
                println!(
                    "Mission {} was already accepted and integrated.",
                    mission_id
                );
                return Ok(());
            }

            if mission.state != plexis_core::state::MissionState::AwaitingAcceptance
                && mission.state != plexis_core::state::MissionState::Accepted
            {
                return Err(format!(
                    "Cannot accept mission: state is '{}', must be 'awaiting_acceptance'",
                    mission.state
                )
                .into());
            }

            if mission.latest_verified_commit.is_none() {
                return Err("Cannot accept: no verified commit found on disk".into());
            }

            let now = chrono::Utc::now().to_rfc3339();
            let _ = mission
                .state
                .transition_to(plexis_core::state::MissionState::Accepted);
            mission.metadata["accepted"] = serde_json::json!(true);
            mission.metadata["accepted_at"] = serde_json::json!(now);

            store.update_mission(&mission).await?;
            println!("✓ Mission {} deliverable explicitly accepted.", mission_id);

            if integrate {
                let res = crate::routes::execute_canonical_integration(
                    &state.store,
                    &state.workspace_locks,
                    &mission_id,
                    branch.as_deref(),
                    message.as_deref(),
                    None,
                    None,
                )
                .await
                .map_err(|(_, msg)| msg)?;

                println!("✓ {}", res.integration_summary);
            } else {
                println!(
                    "Run 'sentinel mission integrate {}' to merge into target branch.",
                    mission_id
                );
            }
        }
        MissionCommands::Reject { id, reason, replan } => {
            let mission_id: MissionId = id.parse()?;
            let mut mission = store
                .get_mission(&mission_id)
                .await?
                .ok_or_else(|| format!("Mission '{}' not found", id))?;

            if mission.state == plexis_core::state::MissionState::Integrated {
                return Err("Cannot reject an already-integrated mission".into());
            }

            if mission.state != plexis_core::state::MissionState::AwaitingAcceptance
                && mission.state != plexis_core::state::MissionState::Accepted
            {
                return Err(format!(
                    "Cannot reject mission: state is '{}', must be 'awaiting_acceptance' or 'accepted'",
                    mission.state
                )
                .into());
            }

            let now = chrono::Utc::now().to_rfc3339();
            if replan {
                let _ = mission
                    .state
                    .transition_to(plexis_core::state::MissionState::Replanning);
                mission.metadata["rejection_reason"] = serde_json::json!(reason);
                mission.metadata["rejected_for_replan_at"] = serde_json::json!(now);
                mission.budget_consumed.planner_iterations += 1;
                store.update_mission(&mission).await?;
                println!(
                    "✓ Mission {} rejected with reason: \"{}\". Queued for adaptive replanning.",
                    mission_id, reason
                );
            } else {
                let _ = mission
                    .state
                    .transition_to(plexis_core::state::MissionState::Rejected);
                mission.metadata["rejected"] = serde_json::json!(true);
                mission.metadata["rejected_at"] = serde_json::json!(now);
                mission.metadata["rejection_reason"] = serde_json::json!(reason);
                store.update_mission(&mission).await?;
                println!(
                    "✓ Mission {} deliverable rejected with reason: \"{}\" (audited).",
                    mission_id, reason
                );
            }
        }
        MissionCommands::Integrate {
            id,
            branch,
            message,
        } => {
            let mission_id: MissionId = id.parse()?;
            let res = crate::routes::execute_canonical_integration(
                &state.store,
                &state.workspace_locks,
                &mission_id,
                branch.as_deref(),
                message.as_deref(),
                None,
                None,
            )
            .await
            .map_err(|(_, msg)| msg)?;

            println!("✓ {}", res.integration_summary);
        }
    }

    Ok(())
}
